fixed same parameters for easily training
fixed following bug：
1. ValueError: could not broadcast input array from shape(43) into shape(88)
2. TypeError: gradient_penalty() got an expected keyword argument 'mode'
3.  TypeError: gradient_penalty()  missing 1 required positional argment: 'sample_mode'
4. have not found path for dataset
and so on ...